<a href="https://colab.research.google.com/github/AliMemon76/DS-A-Lab4-Tasks/blob/main/20SW040_Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1

In [ ]:
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)

print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [ ]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]

print("Original Array:")
print(X)

print("\nArray with Odd Numbers:")
print(Y)


Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array with Odd Numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [ ]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray with consecutive columns
X = np.arange(1, 5)[:, np.newaxis] * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
